import { CurriculumCourse } from './types';

export const AUTHORITATIVE_COURSES: CurriculumCourse[] = [
  {
    id: 'COURSE-GEN0101',
    code: 'GEN 0101',
    title: 'Mathematics for Engineers',
    officialTitle: 'MATHEMATICS FOR ENGINEERS',
    credits: 3.0,
    creditType: 'LEC',
    prerequisites: [],
    academicYear: '2025-2026',
    term: 'First Semester',
    institution: 'University of Perpetual Help System DALTA',
    college: 'College of Engineering',
    sourceSyllabusId: 'SYL-005',
    description: 'This course introduces essential mathematical concepts and techniques for engineering applications. Topics include basic algebra, polynomial operations, and both linear and nonlinear systems of equations. The course covers partial fraction decomposition, engineering trigonometry, and the solution of oblique triangles, emphasizing practical applications in engineering problems. Students will explore trigonometric identities and equations, exponential and logarithmic functions, as well as plane areas and volumes of solids with applications to engineering and science. The course also develops skills in rectangular coordinates, equations of lines, and conic sections, equipping students with analytical and problem-solving tools necessary for advanced engineering mathematics.',
    extractionConfidence: 'HIGH'
  },
  {
    id: 'COURSE-GEN0102',
    code: 'GEN 0102',
    title: 'Calculus 1',
    officialTitle: 'Calculus 1',
    credits: 3.0,
    creditType: 'LEC',
    prerequisites: [],
    academicYear: '2025-2026',
    term: 'First Semester',
    institution: 'University of Perpetual Help System DALTA',
    college: 'College of Engineering',
    sourceSyllabusId: 'SYL-001',
    description: 'This course covers key concepts such as limits, continuity, and the differentiation of various types of functions, including polynomial, trigonometric, exponential, and logarithmic. Students will learn techniques like the chain rule, implicit differentiation, and partial differentiation, as well as applications of derivatives in solving real-world problems such as finding maxima and minima, related rates, and curve sketching. The course also introduces higher-order derivatives and their role in analyzing function behavior.',
    extractionConfidence: 'HIGH'
  },
  {
    id: 'COURSE-GEN0107',
    code: 'GEN 0107',
    title: 'Differential Equations',
    officialTitle: 'Differential Equations',
    credits: 3.0,
    creditType: 'LEC',
    prerequisites: ['Calculus 2'],
    academicYear: '2026-2027',
    term: 'First Semester',
    institution: 'University of Perpetual Help System DALTA',
    college: 'College of Engineering',
    sourceSyllabusId: 'SYL-002',
    description: 'This course provides a rigorous introduction to the analytical and numerical solution of ordinary and partial differential equations, with a distinct focus on applications in mechanical engineering. Students will learn to translate physical phenomena into mathematical models and solve them to analyze mechanical vibrations, structural dynamics, fluid flow, and heat transfer. The course bridges the gap between pure mathematics and core engineering applications like dynamic systems, control theory, and thermofluids.',
    extractionConfidence: 'HIGH'
  },
  {
    id: 'COURSE-GEN0110',
    code: 'GEN 0110/ 0110L',
    title: 'Physics 2 for Engineers',
    officialTitle: 'Physics 2 for Engineers -  Lec/ Lab',
    credits: 3.0,
    creditType: 'LEC_LAB',
    prerequisites: ['Physics 1 for Engineers -  Lec/ Lab'],
    academicYear: '2026-2027',
    term: 'First Semester',
    institution: 'University of Perpetual Help System DALTA',
    college: 'College of Engineering',
    sourceSyllabusId: 'SYL-004',
    description: 'This course provides an in-depth exploration of fundamental concepts in physics, emphasizing the principles governing matter, energy, and their interactions. Topics include elasticity; fluid mechanics; thermal expansion and thermal stress; heat transfer and calorimetry; wave motion and properties; electrostatics; electric circuits; magnetism; and the principles of optics. Students will study image formation using plane and curved mirrors as well as thin lenses, applying geometrical optics to real-world applications. Through lectures, problem-solving sessions, and laboratory experiments, learners will develop analytical skills, quantitative reasoning, and practical competencies essential for understanding and applying physical laws to engineering, technology, and everyday phenomena.',
    extractionConfidence: 'HIGH'
  },
  {
    id: 'COURSE-GEN0161',
    code: 'GEN 0161',
    title: 'Thermodynamics',
    officialTitle: 'Thermodynamics',
    credits: 3.0,
    creditType: 'LEC',
    prerequisites: ['Calculus 2', 'Physics for Engineers'],
    academicYear: '2026-2027',
    term: 'First Semester',
    institution: 'University of Perpetual Help System DALTA',
    college: 'College of Engineering',
    sourceSyllabusId: 'SYL-003',
    description: 'A course dealing with the thermodynamic properties of pure substances, ideal and real gases and the study and application of the laws of thermodynamics in the analysis of processes and cycles. It includes introduction to vapor and gas cycles.',
    extractionConfidence: 'HIGH'
  },
  {
    id: 'COURSE-BSIE3219',
    code: 'BSIE 3219',
    title: 'IE Special Topics 1',
    officialTitle: 'IE Special Topics 1',
    credits: 3.0,
    creditType: 'LEC',
    prerequisites: ['GEN 0110', 'GEN 0110L', 'BSIE 2103', 'GEN 0127'],
    academicYear: '2026-2027',
    term: 'First Semester',
    institution: 'University of Perpetual Help System DALTA',
    college: 'College of Engineering',
    sourceSyllabusId: 'SYL-006',
    description: 'This course provides a comprehensive review and advanced integration of core engineering mathematics, quantitative problem-solving, engineering economy, and applied physical sciences. Designed to reinforce foundational competencies for industrial engineering practice and professional licensure examinations, the course synthesizes advanced algebra, trigonometry, analytic geometry, differential and integral calculus, engineering economic analysis, and engineering mechanics (statics and dynamics). Emphasis is placed on analytical rigor, systematic problem-solving strategies, and practical applications in engineering design, decision-making, and system optimization.',
    extractionConfidence: 'HIGH'
  }
];
