/**
 * Authoritative Problem Family Registry Across All Six Courses
 * Engineering Practice Engine — Phase 5 Six-Course Domain Content Development
 */

import { ProblemFamily } from './types';
import { curriculumRegistry } from '../curriculum/registry';
import { SIX_COURSE_SKILL_EVIDENCE_MAP } from './assessmentEvidence';
import { createFallbackFamily } from './fallbackContent';

export const PROBLEM_FAMILIES_REGISTRY: Record<string, ProblemFamily> = {
  // =========================================================================
  // COURSE: GEN 0101 (Mathematics for Engineers)
  // =========================================================================
  'FAM-GEN0101-OPERATIONS-STD': {
    id: 'FAM-GEN0101-OPERATIONS-STD',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-001',
    supportingSkillIds: [],
    name: 'Real Number Order of Operations Evaluation',
    description: 'Evaluate multi-tier real number arithmetic expressions containing mixed operations, brackets, and negative numbers.',
    purpose: 'Assesses fundamental operational fluency and sign tracking before algebraic manipulation.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['NUMERIC_INPUT', 'MULTIPLE_CHOICE'],
    representationTypes: ['NUMERIC', 'SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['SIGN_PRECEDENCE_ERROR', 'PARENTHESIS_OMISSION'],
    prerequisiteRequirements: [],
    templateIds: ['TMPL-GEN0101-OPERATIONS-STD'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-VARIATION-APP': {
    id: 'FAM-GEN0101-VARIATION-APP',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-004',
    supportingSkillIds: ['SKILL-GEN0101-003'],
    name: 'Direct and Inverse Variation Engineering Modeling',
    description: 'Formulate variation constant equations (y = kx or y = k/x) and solve for unknown engineering parameters.',
    purpose: 'Assesses algebraic translation from engineering proportional relationships to formal equations.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['VERBAL', 'NUMERIC'],
    allowedContexts: ['ENGINEERING', 'PHYSICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['INVERSE_AS_DIRECT_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0101-003'],
    templateIds: ['TMPL-GEN0101-VARIATION-APP'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-QUADRATIC-ROOTS': {
    id: 'FAM-GEN0101-QUADRATIC-ROOTS',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-008',
    supportingSkillIds: ['SKILL-GEN0101-005'],
    name: 'Quadratic Equation Solution by Factoring and Formula',
    description: 'Find real or complex roots of ax^2 + bx + c = 0 using factoring or quadratic formula.',
    purpose: 'Assesses algebraic factoring and radical simplifications.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'NUMERIC_INPUT'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['QUADRATIC_FORMULA_SIGN_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0101-QUADRATIC-ROOTS'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-RADICAL-SIMPLIFY': {
    id: 'FAM-GEN0101-RADICAL-SIMPLIFY',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-006',
    supportingSkillIds: ['SKILL-GEN0101-005'],
    name: 'Radical Simplification and Denominator Rationalization',
    description: 'Simplify radical surds and rationalize denominators involving square roots.',
    purpose: 'Assesses canonical radical forms and fractional exponent arithmetic.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['CLASSIFICATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['RADICAL_SUM_DISTRIBUTION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0101-RADICAL-SIMPLIFY'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-LINEAR-SYSTEMS': {
    id: 'FAM-GEN0101-LINEAR-SYSTEMS',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-009',
    supportingSkillIds: ['SKILL-GEN0101-017'],
    name: 'Linear and Non-Linear Systems of Equations',
    description: 'Solve 2x2, 3x3, and 4x4 linear systems as well as quadratic and circular non-linear systems.',
    purpose: 'Assesses simultaneous linear and non-linear constraint solving, elimination, and substitution.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC', 'NUMERIC'],
    allowedContexts: ['PURE_MATHEMATICS', 'GENERAL_ENGINEERING'],
    difficultyRange: [1, 4],
    misconceptionTargets: ['DETERMINANT_CROSS_SIGN_ERROR', 'SIGN_SUBSTITUTION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: [
      'TMPL-GEN0101-LINEAR-SYSTEMS',
      'TMPL-GEN0101-SYSTEMS-3X3',
      'TMPL-GEN0101-SYSTEMS-4X4',
      'TMPL-GEN0101-SYSTEMS-NONLINEAR'
    ],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-TRIG-TRIANGLE': {
    id: 'FAM-GEN0101-TRIG-TRIANGLE',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-013',
    supportingSkillIds: ['SKILL-GEN0101-008'],
    name: 'Right and Oblique Triangle Trigonometric Solution',
    description: 'Solve triangles using standard trigonometric ratios, Law of Sines, or Law of Cosines for elevation and surveying.',
    purpose: 'Assesses geometric and trigonometric modeling of structural surveying and force angles.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['NUMERIC', 'VERBAL', 'GRAPHICAL'],
    allowedContexts: ['GENERAL_ENGINEERING', 'PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['DEGREE_RADIAN_CONFUSION', 'LAW_OF_COSINES_SIGN_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-008'],
    templateIds: ['TMPL-GEN0101-TRIG-TRIANGLE'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-PARTIAL-FRACTIONS': {
    id: 'FAM-GEN0101-PARTIAL-FRACTIONS',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-003',
    supportingSkillIds: ['SKILL-GEN0101-005'],
    name: 'Partial Fraction Decomposition for Distinct Linear Factors',
    description: 'Decompose rational algebraic fractions into sums of simpler partial fractions A/(x-a) + B/(x-b).',
    purpose: 'Prepares students for analytical integration and inverse Laplace transforms.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['EQUATING_COEFFICIENTS_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-003'],
    templateIds: ['TMPL-GEN0101-PARTIAL-FRACTIONS'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-WORD-PROBLEMS': {
    id: 'FAM-GEN0101-WORD-PROBLEMS',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-007',
    supportingSkillIds: ['SKILL-GEN0101-009'],
    name: 'Algebraic Mixture and Uniform Motion Engineering Word Problems',
    description: 'Translate physical word scenarios into linear equations (Concentration mixture C1V1 + C2V2 = CfVf, Distance = Rate * Time).',
    purpose: 'Assesses mathematical modeling of physical conservation and motion.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['VERBAL', 'NUMERIC'],
    allowedContexts: ['ENGINEERING', 'GENERAL_ENGINEERING'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['MIXTURE_MASS_CONSERVATION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-009'],
    templateIds: ['TMPL-GEN0101-WORD-PROBLEMS'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-FUNCTIONS': {
    id: 'FAM-GEN0101-FUNCTIONS',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-010',
    supportingSkillIds: ['SKILL-GEN0101-005'],
    name: 'Function Domain, Range, Composition, and Inverses',
    description: 'Determine natural domains of algebraic functions, compose f(g(x)), and find algebraic inverses f^(-1)(x).',
    purpose: 'Assesses foundational functional relations, domain restrictions, composition mappings, and inverse transformations.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'MULTIPLE_CHOICE', 'SYMBOLIC_INPUT'],
    representationTypes: ['SYMBOLIC', 'NUMERIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 4],
    misconceptionTargets: ['REVERSED_COMPOSITION_ERROR', 'RECIPROCAL_AS_INVERSE_ERROR', 'DOMAIN_INEQUALITY_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0101-FUNCTIONS'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },
  'FAM-GEN0101-EXP-LOG': {
    id: 'FAM-GEN0101-EXP-LOG',
    courseId: 'COURSE-GEN0101',
    primarySkillId: 'SKILL-GEN0101-011',
    supportingSkillIds: ['SKILL-GEN0101-006', 'SKILL-GEN0101-010'],
    name: 'Exponential and Logarithmic Equations',
    description: 'Solve exponential equations, logarithmic equations, and quadratic-in-form exponential systems with extraneous root checks.',
    purpose: 'Assesses transcendental equation solving, logarithm property applications, and extraneous root verification.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'MULTIPLE_CHOICE', 'SYMBOLIC_INPUT'],
    representationTypes: ['SYMBOLIC', 'NUMERIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 4],
    misconceptionTargets: ['EXTRANEOUS_ROOT_OMISSION', 'LOG_PROPERTY_DISTRIBUTION_ERROR', 'BASE_LOG_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0101-006', 'SKILL-GEN0101-010'],
    templateIds: ['TMPL-GEN0101-EXP-LOG'],
    domainValidatorType: 'MATH_FOR_ENGINEERS',
    status: 'ACTIVE'
  },

  // =========================================================================
  // COURSE: GEN 0102 (Calculus 1 — Complete 15-Skill Coverage)
  // =========================================================================
  'FAM-GEN0102-LIMITS-ALG': {
    id: 'FAM-GEN0102-LIMITS-ALG',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-001',
    supportingSkillIds: ['SKILL-GEN0101-005'],
    name: 'Algebraic Limits with Removable Indeterminate Forms (0/0)',
    description: 'Evaluate rational algebraic limits via difference of squares factoring, polynomial division, and cancellation.',
    purpose: 'Assesses algebraic limit evaluation and indeterminate form identification.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION', 'ERROR_ANALYSIS'],
    supportedFormats: ['SYMBOLIC_INPUT', 'NUMERIC_INPUT'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['DIRECT_SUBSTITUTION_ZERO_ZERO_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-005'],
    templateIds: ['TMPL-LIMIT-POLY-CANCEL'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-POWER-STD': {
    id: 'FAM-GEN0102-POWER-STD',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-002',
    supportingSkillIds: ['SKILL-GEN0101-005'],
    name: 'Polynomial Power Rule Differentiation',
    description: 'Differentiate polynomial terms term-by-term using the fundamental Power Rule d/dx[x^n] = n*x^(n-1).',
    purpose: 'Establishes baseline derivative mechanics for polynomial expressions.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['ERROR_ANALYSIS', 'METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 2],
    misconceptionTargets: ['POWER_RULE_NO_DECREMENT'],
    prerequisiteRequirements: ['SKILL-GEN0101-005'],
    templateIds: ['TMPL-POWER-POLY-STD'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-PRODUCT-STD': {
    id: 'FAM-GEN0102-PRODUCT-STD',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-003',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Product Rule Differentiation of Polynomial and Transcendental Functions',
    description: 'Differentiate products of two distinct functions using (u*v)\' = u\'v + uv\'.',
    purpose: 'Assesses execution of Product Rule and prevents naive product distribution misconceptions.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION', 'ERROR_ANALYSIS'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['NAIVE_PRODUCT_DISTRIBUTION'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-PRODUCT-POLY-TRIG'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-QUOTIENT-STD': {
    id: 'FAM-GEN0102-QUOTIENT-STD',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-004',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Quotient Rule Differentiation of Rational Expressions',
    description: 'Differentiate quotients of functions using (u/v)\' = (u\'v - uv\') / v^2.',
    purpose: 'Assesses execution of Quotient Rule, numerator subtraction ordering, and denominator squaring.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION', 'ERROR_ANALYSIS'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['QUOTIENT_ORDER_REVERSAL', 'DENOMINATOR_SQUARE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-QUOTIENT-POLY-POLY'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-CHAIN-POLY': {
    id: 'FAM-GEN0102-CHAIN-POLY',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-005',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Composite Polynomial Power Chain Rule',
    description: 'Differentiate functions of the form y = (g(x))^n using the General Power Rule.',
    purpose: 'Assesses recognition of inner/outer structure and multiplication by inner derivative g\'(x).',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['ERROR_ANALYSIS', 'METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 4],
    misconceptionTargets: ['OMISSION_OF_INNER_DERIVATIVE', 'POWER_RULE_NO_DECREMENT'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-CHAIN-POLY-STD', 'TMPL-CHAIN-POWER-POLYNOMIAL'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-CHAIN-TRIG': {
    id: 'FAM-GEN0102-CHAIN-TRIG',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-005',
    supportingSkillIds: ['SKILL-GEN0102-006'],
    name: 'Composite Trigonometric Chain Rule',
    description: 'Differentiate expressions of the form sin(g(x)) and cos(g(x)).',
    purpose: 'Assesses transcendental Chain Rule composition with argument differentiation.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['MISSING_INNER_DERIVATIVE', 'OMISSION_OF_INNER_DERIVATIVE', 'TRIG_ARGUMENT_DERIVATIVE_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-006'],
    templateIds: ['TMPL-CHAIN-TRIG-POLY'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-CHAIN-ERROR': {
    id: 'FAM-GEN0102-CHAIN-ERROR',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-005',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Chain Rule Flawed Derivation Diagnostic Error Analysis',
    description: 'Given student work with omitted inner derivative, diagnose exact conceptual mistake.',
    purpose: 'Assesses meta-cognitive debugging and precise misconception identification.',
    primaryEvidenceType: 'ERROR_ANALYSIS',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['MULTIPLE_CHOICE', 'ERROR_ANALYSIS'],
    representationTypes: ['SYMBOLIC', 'VERBAL'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['MISSING_INNER_DERIVATIVE', 'OMISSION_OF_INNER_DERIVATIVE'],
    prerequisiteRequirements: ['SKILL-GEN0102-005'],
    templateIds: ['TMPL-CHAIN-ERROR-DIAG'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-CHAIN-RECOG': {
    id: 'FAM-GEN0102-CHAIN-RECOG',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-005',
    supportingSkillIds: ['SKILL-GEN0102-002', 'SKILL-GEN0102-003', 'SKILL-GEN0102-004'],
    name: 'Differentiation Rule Discrimination (Chain vs Product vs Quotient)',
    description: 'Given an algebraic expression, identify the primary required differentiation theorem before calculation.',
    purpose: 'Assesses rule recognition and structural awareness before execution.',
    primaryEvidenceType: 'METHOD_RECOGNITION',
    secondaryEvidenceTypes: ['CLASSIFICATION'],
    supportedFormats: ['MULTIPLE_CHOICE', 'MATCHING'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 2],
    misconceptionTargets: ['PRODUCT_VS_CHAIN_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-005'],
    templateIds: ['TMPL-CHAIN-METHOD-RECOG'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-CHAIN-APP': {
    id: 'FAM-GEN0102-CHAIN-APP',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-005',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Kinematics Instantaneous Velocity from Composite Displacement Models',
    description: 'Calculate instantaneous velocity v(t) = s\'(t) from composite displacement law s(t) = (at^2 + b)^n.',
    purpose: 'Assesses physical application of the Chain Rule in robotics and mechanics contexts.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['SYMBOLIC', 'NUMERIC', 'VERBAL', 'PHYSICAL'],
    allowedContexts: ['PHYSICS', 'KINEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['OMISSION_OF_INNER_DERIVATIVE', 'UNIT_POWER_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-005'],
    templateIds: ['TMPL-CHAIN-KINEMATICS-APP'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-TRIG-CIRCULAR': {
    id: 'FAM-GEN0102-TRIG-CIRCULAR',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-006',
    supportingSkillIds: ['SKILL-GEN0101-010'],
    name: 'Circular Trigonometric Function Differentiation (Sin, Cos, Tan, Sec)',
    description: 'Differentiate standard circular trigonometric expressions using fundamental derivative identities.',
    purpose: 'Assesses exact sign tracking and trigonometric derivative identities.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['COSINE_DERIVATIVE_SIGN_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-010'],
    templateIds: ['TMPL-GEN0102-TRIG-CIRCULAR'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-EXP-LOG': {
    id: 'FAM-GEN0102-EXP-LOG',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-008',
    supportingSkillIds: ['SKILL-GEN0101-012'],
    name: 'Exponential and Natural Logarithmic Function Differentiation',
    description: 'Differentiate expressions involving e^(kx) and ln(ax + b).',
    purpose: 'Assesses exponential invariance and logarithmic reciprocal derivative properties.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['LOG_ARGUMENT_RECIPROCAL_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-012'],
    templateIds: ['TMPL-GEN0102-EXP-LOG'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-IMPLICIT-DIFF': {
    id: 'FAM-GEN0102-IMPLICIT-DIFF',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-009',
    supportingSkillIds: ['SKILL-GEN0102-005'],
    name: 'Implicit Bivariate Algebraic Differentiation for dy/dx',
    description: 'Differentiate implicit curves f(x, y) = c with respect to x and solve algebraically for dy/dx.',
    purpose: 'Assesses application of Chain Rule to dependent variable y and algebraic isolation of dy/dx.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION', 'ERROR_ANALYSIS'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['IMPLICIT_DYDX_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-005'],
    templateIds: ['TMPL-GEN0102-IMPLICIT-DIFF'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-HIGHER-ORDER': {
    id: 'FAM-GEN0102-HIGHER-ORDER',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-011',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Higher-Order Successive Derivative Evaluation',
    description: 'Compute second and third derivatives d^2y/dx^2, d^3y/dx^3 of polynomial and transcendental functions.',
    purpose: 'Prepares students for concavity analysis and second-order differential equations.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'NUMERIC_INPUT'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['SUCCESSIVE_POWER_DECREMENT_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-GEN0102-HIGHER-ORDER'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-PARTIAL-DERIV': {
    id: 'FAM-GEN0102-PARTIAL-DERIV',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-010',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'First-Order Partial Derivative Evaluation with Constant Variable Holding',
    description: 'Evaluate partial derivatives del f / del x and del f / del y for multivariable surfaces f(x, y).',
    purpose: 'Assesses treating un-differentiated independent variables as constants.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['TREATING_VARIABLE_AS_DEPENDENT'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-GEN0102-PARTIAL-DERIV'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-RELATED-RATES': {
    id: 'FAM-GEN0102-RELATED-RATES',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-015',
    supportingSkillIds: ['SKILL-GEN0102-008'],
    name: 'Related Rates Geometric and Physical Change Modeling',
    description: 'Model interconnected physical rates of change with respect to time (expanding circular ripples, ladder sliding, conical tanks).',
    purpose: 'Assesses implicit time differentiation of geometric constraint equations.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['VERBAL', 'NUMERIC', 'SYMBOLIC'],
    allowedContexts: ['PHYSICS', 'GENERAL_ENGINEERING'],
    difficultyRange: [3, 5],
    misconceptionTargets: ['SUBSTITUTING_BEFORE_DIFFERENTIATION'],
    prerequisiteRequirements: ['SKILL-GEN0102-008'],
    templateIds: ['TMPL-GEN0102-RELATED-RATES'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-TANGENT-APP': {
    id: 'FAM-GEN0102-TANGENT-APP',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-012',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Tangent and Normal Line Equation Construction',
    description: 'Calculate slope m = f\'(x0) and formulate tangent line equation y - y0 = m(x - x0).',
    purpose: 'Assesses geometric interpretation of the derivative at a point.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC', 'GRAPHICAL'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['SLOPE_EVALUATION_POINT_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-TANGENT-LINE-STD'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-CURVE-SKETCH': {
    id: 'FAM-GEN0102-CURVE-SKETCH',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-013',
    supportingSkillIds: ['SKILL-GEN0102-009'],
    name: 'Critical Point Classification, Inflection Points, and Concavity Analysis',
    description: 'Find critical points f\'(x) = 0 and determine local extrema and concavity via Second Derivative Test.',
    purpose: 'Assesses structural curve behavior interpretation and extrema classification.',
    primaryEvidenceType: 'CLASSIFICATION',
    secondaryEvidenceTypes: ['GRAPH_READING', 'INTERPRETATION'],
    supportedFormats: ['MULTIPLE_CHOICE', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC', 'VERBAL'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['FIRST_VS_SECOND_DERIVATIVE_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-009'],
    templateIds: ['TMPL-GEN0102-CURVE-SKETCH'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-OPTIMIZATION': {
    id: 'FAM-GEN0102-OPTIMIZATION',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-014',
    supportingSkillIds: ['SKILL-GEN0102-013'],
    name: 'Engineering Geometry and Cost Optimization Modeling',
    description: 'Formulate single-variable objective functions subject to geometric/cost constraints and maximize/minimize via calculus.',
    purpose: 'Assesses translation of physical design constraints into mathematical extreme value models.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['VERBAL', 'NUMERIC', 'SYMBOLIC'],
    allowedContexts: ['GENERAL_ENGINEERING'],
    difficultyRange: [3, 5],
    misconceptionTargets: ['CONSTRAINT_SUBSTITUTION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0102-013'],
    templateIds: ['TMPL-GEN0102-OPTIMIZATION'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },
  'FAM-GEN0102-DIFFERENTIALS': {
    id: 'FAM-GEN0102-DIFFERENTIALS',
    courseId: 'COURSE-GEN0102',
    primarySkillId: 'SKILL-GEN0102-015',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Differentials and Tangent Linear Approximation for Error Estimation',
    description: 'Use differentials dy = f\'(x) dx to estimate propagated error and compute linear local approximations.',
    purpose: 'Assesses linear approximation formulas in measurement tolerance analysis.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['NUMERIC', 'SYMBOLIC'],
    allowedContexts: ['GENERAL_ENGINEERING'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['DELTA_X_SCALE_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-GEN0102-DIFFERENTIALS'],
    domainValidatorType: 'MATH',
    status: 'ACTIVE'
  },

  // =========================================================================
  // COURSE: GEN 0107 (Differential Equations)
  // =========================================================================
  'FAM-GEN0107-CLASSIFY-ORDER': {
    id: 'FAM-GEN0107-CLASSIFY-ORDER',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-001',
    supportingSkillIds: [],
    name: 'Differential Equation Classification by Order and Linearity',
    description: 'Identify order, degree, and linearity of ordinary and partial differential equations.',
    purpose: 'Assesses foundational ODE taxonomic categorization before method selection.',
    primaryEvidenceType: 'CLASSIFICATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['MULTIPLE_CHOICE', 'MATCHING'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 2],
    misconceptionTargets: ['DEGREE_VS_ORDER_CONFUSION', 'NONLINEAR_COEFFICIENT_CONFUSION'],
    prerequisiteRequirements: [],
    templateIds: ['TMPL-GEN0107-CLASSIFY-ORDER'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-SEPARABLE-STD': {
    id: 'FAM-GEN0107-SEPARABLE-STD',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-003',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Separable First-Order ODE Analytical Integration',
    description: 'Solve first-order ODEs dy/dx = g(x)h(y) by isolating variables and integrating both sides.',
    purpose: 'Assesses separation of differential variables and integration mechanics.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION', 'ERROR_ANALYSIS'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['SEPARATION_SIGN_ERROR', 'OMISSION_OF_INTEGRATION_CONSTANT'],
    prerequisiteRequirements: ['SKILL-GEN0102-002'],
    templateIds: ['TMPL-GEN0107-SEPARABLE-STD'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-LINEAR-1ST-IF': {
    id: 'FAM-GEN0107-LINEAR-1ST-IF',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-006',
    supportingSkillIds: ['SKILL-GEN0102-008'],
    name: 'First-Order Linear ODE via Integrating Factor',
    description: 'Solve dy/dx + P(x)y = Q(x) by computing integrating factor mu(x) = exp(integral P(x)dx).',
    purpose: 'Assesses the integrating factor algorithm and Product Rule integration.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['MULTI_STEP_SOLUTION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS', 'ENGINEERING'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['INTEGRATING_FACTOR_SIGN_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0102-008'],
    templateIds: ['TMPL-GEN0107-LINEAR-1ST-IF'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-EXACT-ODE': {
    id: 'FAM-GEN0107-EXACT-ODE',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-005',
    supportingSkillIds: ['SKILL-GEN0102-010'],
    name: 'Exact Differential Equations and Test for Exactness',
    description: 'Test M(x, y) dx + N(x, y) dy = 0 for exactness (del M / del y = del N / del x) and find potential function psi(x, y) = C.',
    purpose: 'Assesses exact differential testing and multivariable potential reconstruction.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [3, 5],
    misconceptionTargets: ['EXACTNESS_PARTIAL_DERIVATIVE_CROSS_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0102-010'],
    templateIds: ['TMPL-GEN0107-EXACT-ODE'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMOGENEOUS-VX': {
    id: 'FAM-GEN0107-HOMOGENEOUS-VX',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'SOLVE_GENERAL_SOLUTION',
    archetypeId: 'ARCH-HOMO-DIRECT-RATIO',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    name: 'First-Order Homogeneous Differential Equations (Direct Ratio y = vx)',
    description: 'Solve first-order homogeneous differential equations dy/dx = F(y/x) using the substitution y = vx and variable separation.',
    purpose: 'Assesses recognition of homogeneous equations of degree 0, algebraic substitution y = vx, separation in v, and general solution construction.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION', 'METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0107-HOMOGENEOUS-VX'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-DIFF-FORM': {
    id: 'FAM-GEN0107-HOMO-DIFF-FORM',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'SOLVE_GENERAL_SOLUTION',
    archetypeId: 'ARCH-HOMO-DIFF-FORM',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    name: 'Homogeneous ODE Differential Form Rearrangement M dx + N dy = 0',
    description: 'Solve homogeneous differential equations in differential form M dx + N dy = 0 requiring algebraic rearrangement.',
    purpose: 'Assesses ability to factor and rearrange differential expressions before applying substitution y = vx (dy = v dx + x dv) to find general solution.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0107-HOMO-DIFF-FORM'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-DUAL-SUB': {
    id: 'FAM-GEN0107-HOMO-DUAL-SUB',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'SOLVE_GENERAL_SOLUTION',
    archetypeId: 'ARCH-HOMO-DUAL-SUB',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    name: 'Homogeneous ODE Dual Monomial Substitution (x = vy vs y = vx)',
    description: 'Solve homogeneous equations where dx coefficient is simpler monomial, making x = vy structurally superior to y = vx.',
    purpose: 'Evaluates pedagogical criterion from Castro: selecting x = vy or y = vx to simplify integration and solve for general solution.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION', 'DIRECT_CALCULATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0107-HOMO-DUAL-SUB'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-PARTIAL-FRAC': {
    id: 'FAM-GEN0107-HOMO-PARTIAL-FRAC',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'SOLVE_GENERAL_SOLUTION',
    archetypeId: 'ARCH-HOMO-PARTIAL-FRAC',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    name: 'Homogeneous ODE with Quadratic/Partial Fraction Separation',
    description: 'Solve homogeneous ODEs where substitution y = vx produces a quadratic denominator in v requiring partial fractions.',
    purpose: 'Evaluates multi-tier mathematical competence combining homogeneous substitution with partial fractions.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [3, 4],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0107-HOMO-PARTIAL-FRAC'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-INVERSE-TRIG': {
    id: 'FAM-GEN0107-HOMO-INVERSE-TRIG',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'SOLVE_GENERAL_SOLUTION',
    archetypeId: 'ARCH-HOMO-INVERSE-TRIG',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    name: 'Homogeneous ODE with Irreducible Quadratic Denominator / Inverse Trig Integration',
    description: 'Solve homogeneous ODEs where substitution y = vx leads to an irreducible quadratic denominator (1 + v^2) integrating to arctan(y/x).',
    purpose: 'Evaluates Castro Spread 14 Problem 1 integration archetype combining homogeneous substitution with inverse tangent solutions.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [3, 4],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0107-HOMO-INVERSE-TRIG'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-TRANSCENDENTAL': {
    id: 'FAM-GEN0107-HOMO-TRANSCENDENTAL',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'SOLVE_GENERAL_SOLUTION',
    archetypeId: 'ARCH-HOMO-TRANSCENDENTAL',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    name: 'Homogeneous ODE with Transcendental Trigonometric / Radical Separation',
    description: 'Solve homogeneous ODEs involving transcendental functions of (y/x) or radical expressions.',
    purpose: 'Evaluates Castro Spread 17 Problem 14 transcendental homogeneous archetype requiring trigonometric separation.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [4, 5],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0107-HOMO-TRANSCENDENTAL'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-IVP': {
    id: 'FAM-GEN0107-HOMO-IVP',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'SOLVE_INITIAL_VALUE_PROBLEM',
    archetypeId: 'ARCH-HOMO-IVP',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    name: 'Homogeneous Initial Value Problem (Particular Solution)',
    description: 'Solve homogeneous first-order initial value problems to find the unique particular solution.',
    purpose: 'Evaluates full solution lifecycle: substitution y = vx, integration, and particular constant determination.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-003', 'SKILL-GEN0101-005'],
    templateIds: ['TMPL-GEN0107-HOMO-IVP'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-DEGREE-TEST': {
    id: 'FAM-GEN0107-HOMO-DEGREE-TEST',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'ANALYZE_HOMOGENEITY_DEGREE',
    archetypeId: 'ARCH-HOMO-DEGREE-TEST',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-001'],
    name: 'Euler Homogeneity & Degree Verification Test',
    description: 'Verify whether a given function or differential equation is homogeneous and determine its degree n using Euler scaling.',
    purpose: 'Directly reinforces Castro foundational concept: testing f(tx, ty) = t^n f(x, y) before applying substitution.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'MULTIPLE_CHOICE', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 2],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-001'],
    templateIds: ['TMPL-GEN0107-HOMO-DEGREE-TEST'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-HOMO-VERIFY': {
    id: 'FAM-GEN0107-HOMO-VERIFY',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_first_order_homogeneous_y_vx',
    taskType: 'VERIFY_SOLUTION',
    archetypeId: 'ARCH-HOMO-VERIFY',
    conceptMetadata: {
      conceptId: 'de_first_order_homogeneous_y_vx',
      order: 1,
      linearity: 'MAY_BE_NONLINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'NOT_APPLICABLE',
      expectedMethod: 'SUBSTITUTION_Y_EQUALS_VX'
    },
    supportingSkillIds: ['SKILL-GEN0107-001'],
    name: 'Homogeneous ODE Solution Verification',
    description: 'Verify whether a proposed algebraic relation satisfies a given homogeneous differential equation.',
    purpose: 'Cultivates backward verification competence and differential substitution.',
    primaryEvidenceType: 'MULTI_STEP_SOLUTION',
    secondaryEvidenceTypes: ['METHOD_RECOGNITION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS'],
    difficultyRange: [1, 2],
    misconceptionTargets: ['CHAIN_RULE_POWERS_BASE_DERIVATIVE_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0107-001'],
    templateIds: ['TMPL-GEN0107-HOMO-VERIFY'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-2ND-ORDER-HOMO': {
    id: 'FAM-GEN0107-2ND-ORDER-HOMO',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-004',
    conceptId: 'de_second_order_linear_homogeneous_constant_coeff',
    conceptMetadata: {
      conceptId: 'de_second_order_linear_homogeneous_constant_coeff',
      order: 2,
      linearity: 'LINEAR',
      homogeneity: 'HOMOGENEOUS',
      coefficientType: 'CONSTANT',
      expectedMethod: 'CHARACTERISTIC_EQUATION'
    },
    supportingSkillIds: ['SKILL-GEN0101-006'],
    name: 'Second-Order Linear Homogeneous ODEs with Constant Coefficients',
    description: 'Solve ay\'\' + by\' + cy = 0 by finding characteristic equation roots (distinct real, repeated, complex conjugate).',
    purpose: 'Assesses characteristic polynomial root analysis and fundamental solution set construction.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['CLASSIFICATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS', 'PHYSICS'],
    difficultyRange: [1, 4],
    misconceptionTargets: ['REPEATED_ROOT_FACTOR_X_OMISSION'],
    prerequisiteRequirements: ['SKILL-GEN0101-006'],
    templateIds: ['TMPL-GEN0107-2ND-ORDER-HOMO'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-LAPLACE-TRANSFORM': {
    id: 'FAM-GEN0107-LAPLACE-TRANSFORM',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-009',
    supportingSkillIds: ['SKILL-GEN0101-015'],
    name: 'Direct and Inverse Laplace Transforms Table Evaluation',
    description: 'Evaluate Laplace transforms L{f(t)} and inverse transforms L^-1{F(s)} using linearity and standard transform pairs.',
    purpose: 'Assesses operational calculus and s-domain mapping.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['TABLE_INTERPRETATION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS', 'CIRCUITS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['LAPLACE_SHIFT_EXPONENTIAL_SIGN_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-015'],
    templateIds: ['TMPL-GEN0107-LAPLACE-TRANSFORM'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-IVP-FIRST-ORDER': {
    id: 'FAM-GEN0107-IVP-FIRST-ORDER',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-002',
    supportingSkillIds: ['SKILL-GEN0102-002'],
    name: 'Initial Value Problem (IVP) Particular Solution Evaluation',
    description: 'Solve ODE subject to initial boundary condition y(x0) = y0 to determine particular constant C.',
    purpose: 'Assesses boundary value substitution and particular solution isolation.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['MULTI_STEP_SOLUTION'],
    supportedFormats: ['SYMBOLIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['SYMBOLIC'],
    allowedContexts: ['PURE_MATHEMATICS', 'PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['INITIAL_CONDITION_SUBSTITUTION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-002'],
    templateIds: ['TMPL-GEN0107-IVP-FIRST-ORDER'],
    domainValidatorType: 'ODE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-MIXING-TANK': {
    id: 'FAM-GEN0107-MIXING-TANK',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-008',
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0107-006'],
    name: 'Transient Physical System Mixing Tank Concentration Modeling',
    description: 'Model transient solute mass in well-stirred tanks: dq/dt = rate_in * c_in - (rate_out / V(t)) * q.',
    purpose: 'Assesses first-order linear ODE modeling of chemical engineering mixing processes.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['VERBAL', 'NUMERIC', 'SYMBOLIC'],
    allowedContexts: ['GENERAL_ENGINEERING', 'PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['MIXING_OUTFLOW_VOLUME_DRIFT_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-003'],
    templateIds: ['TMPL-GEN0107-MIXING-TANK'],
    domainValidatorType: 'ODE',
    conceptId: 'de_first_order_applications',
    taskType: 'SOLVE_INITIAL_VALUE_PROBLEM',
    archetypeId: 'ARCH-APP-MIXING-CONSTANT-VOL',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-APP-MIXING-CONSTANT': {
    id: 'FAM-GEN0107-APP-MIXING-CONSTANT',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-008',
    supportingSkillIds: ['SKILL-GEN0107-003', 'SKILL-GEN0107-006'],
    name: 'Castro Constant-Volume Mixing Tank Solute Dynamics',
    description: 'Model solute mass in tanks with equal inflow and outflow rates: dm/dt = R_in C_in - (R_out / V0) m.',
    purpose: 'Evaluates Castro Spread 48 Problem 24 dynamic mass balance and threshold time calculations.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['VERBAL', 'SYMBOLIC', 'NUMERIC'],
    allowedContexts: ['GENERAL_ENGINEERING', 'PHYSICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['MIXING_OUTFLOW_VOLUME_DRIFT_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-003'],
    templateIds: ['TMPL-GEN0107-APP-MIX-CONST-SOLVE', 'TMPL-GEN0107-APP-MIX-CONST-THRESHOLD'],
    domainValidatorType: 'ODE',
    conceptId: 'de_first_order_applications',
    taskType: 'SOLVE_INITIAL_VALUE_PROBLEM',
    archetypeId: 'ARCH-APP-MIXING-CONSTANT-VOL',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-APP-MIXING-VARIABLE': {
    id: 'FAM-GEN0107-APP-MIXING-VARIABLE',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-008',
    supportingSkillIds: ['SKILL-GEN0107-006'],
    name: 'Castro Variable-Volume Liquid Mixture Accumulation',
    description: 'Model solute concentration in tanks where inflow rate != outflow rate with integrating factor mu(t) = (V0 + delta_R t)^n.',
    purpose: 'Evaluates variable-coefficient first-order linear ODE modeling of hydraulic filling/draining.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['VERBAL', 'SYMBOLIC', 'NUMERIC'],
    allowedContexts: ['GENERAL_ENGINEERING', 'PHYSICS'],
    difficultyRange: [4, 5],
    misconceptionTargets: ['MIXING_OUTFLOW_VOLUME_DRIFT_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-006'],
    templateIds: ['TMPL-GEN0107-APP-MIX-VAR-ACCUM'],
    domainValidatorType: 'ODE',
    conceptId: 'de_first_order_applications',
    taskType: 'MODEL_AND_SOLVE',
    archetypeId: 'ARCH-APP-MIXING-VARIABLE-VOL',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-APP-MIXING-DILUTION': {
    id: 'FAM-GEN0107-APP-MIXING-DILUTION',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-008',
    supportingSkillIds: ['SKILL-GEN0107-003'],
    name: 'Castro Pure Solvent Dilution Washout Kinetics',
    description: 'Model exponential dilution washout of initial solute when pure solvent (C_in = 0) flushes a reservoir: dm/dt = -(R/V)m.',
    purpose: 'Evaluates separable exponential decay formulation in hydraulic flushing.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['VERBAL', 'SYMBOLIC'],
    allowedContexts: ['GENERAL_ENGINEERING', 'PHYSICS'],
    difficultyRange: [1, 2],
    misconceptionTargets: ['MIXING_OUTFLOW_VOLUME_DRIFT_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-003'],
    templateIds: ['TMPL-GEN0107-APP-MIX-DILUTION-FLUSH', 'TMPL-GEN0107-APP-MIX-WASHOUT-TIME'],
    domainValidatorType: 'ODE',
    conceptId: 'de_first_order_applications',
    taskType: 'SOLVE_INITIAL_VALUE_PROBLEM',
    archetypeId: 'ARCH-APP-MIXING-PURE-FLUSH',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-APP-COOLING-NEWTON': {
    id: 'FAM-GEN0107-APP-COOLING-NEWTON',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-008',
    supportingSkillIds: ['SKILL-GEN0107-003'],
    name: 'Castro Newton Law of Cooling & Thermal Dissipation',
    description: 'Model transient temperature of objects cooling in an ambient medium: dT/dt = -k(T - T_m).',
    purpose: 'Evaluates Castro Spread 44 & 45 Newton cooling formulations, rate parameter determination, and target times.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['VERBAL', 'NUMERIC', 'SYMBOLIC'],
    allowedContexts: ['PHYSICS', 'HEAT_TRANSFER'],
    difficultyRange: [1, 4],
    misconceptionTargets: ['AMBIENT_TEMPERATURE_SIGN_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-003'],
    templateIds: [
      'TMPL-GEN0107-APP-COOL-DIRECT',
      'TMPL-GEN0107-APP-COOL-TIME-TARGET',
      'TMPL-GEN0107-APP-COOL-TWO-POINT',
      'TMPL-GEN0107-APP-HEAT-DIRECT',
      'TMPL-GEN0107-APP-HEAT-TIME-TARGET'
    ],
    domainValidatorType: 'ODE',
    conceptId: 'de_first_order_applications',
    taskType: 'SOLVE_INITIAL_VALUE_PROBLEM',
    archetypeId: 'ARCH-APP-COOLING-CONSTANT-AMBIENT',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-APP-GROWTH-DECAY': {
    id: 'FAM-GEN0107-APP-GROWTH-DECAY',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-008',
    supportingSkillIds: ['SKILL-GEN0107-003'],
    name: 'Castro Radioactive Decomposition & Half-Life Kinetics',
    description: 'Model first-order radioactive decay dm/dt = -km and Malthusian population growth dP/dt = kP.',
    purpose: 'Evaluates Castro Spread 47 Problem 13 radioactive decomposition models and population kinetics.',
    primaryEvidenceType: 'MODELING',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['NUMERIC_INPUT', 'SYMBOLIC_INPUT'],
    representationTypes: ['VERBAL', 'NUMERIC'],
    allowedContexts: ['PHYSICS', 'GENERAL_ENGINEERING'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['HALF_LIFE_FORMULA_INVERSION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-003'],
    templateIds: [
      'TMPL-GEN0107-APP-DECAY-HALF-LIFE',
      'TMPL-GEN0107-APP-POP-GROWTH-IVP',
      'TMPL-GEN0107-APP-POP-DOUBLING'
    ],
    domainValidatorType: 'ODE',
    conceptId: 'de_first_order_applications',
    taskType: 'CALCULATE_THRESHOLD_TIME',
    archetypeId: 'ARCH-APP-DECAY-HALF-LIFE',
    status: 'ACTIVE'
  },
  'FAM-GEN0107-APP-ORTHOGONAL': {
    id: 'FAM-GEN0107-APP-ORTHOGONAL',
    courseId: 'COURSE-GEN0107',
    primarySkillId: 'SKILL-GEN0107-008',
    supportingSkillIds: ['SKILL-GEN0107-003'],
    name: 'Castro Orthogonal Trajectories of Planar Curves',
    description: 'Determine the family of orthogonal trajectory curves to a given family by replacing dy/dx with -dx/dy.',
    purpose: 'Evaluates Castro Spread 49 & 50 orthogonal trajectories to lines, parabolas, and concentric circles.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION', 'MULTI_STEP_SOLUTION'],
    supportedFormats: ['SYMBOLIC_INPUT'],
    representationTypes: ['SYMBOLIC', 'VERBAL'],
    allowedContexts: ['PURE_MATHEMATICS', 'PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['ORTHOGONAL_SLOPE_INVERSION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0107-003'],
    templateIds: ['TMPL-GEN0107-APP-ORTHO-TRAJECTORIES'],
    domainValidatorType: 'ODE',
    conceptId: 'de_first_order_applications',
    taskType: 'SOLVE_GENERAL_SOLUTION',
    archetypeId: 'ARCH-APP-ORTHOGONAL-ALGEBRAIC',
    status: 'ACTIVE'
  },

  // =========================================================================
  // COURSE: GEN 0110 (Physics 2 for Engineers - Lec/Lab)
  // =========================================================================
  'FAM-GEN0110-FLUID-PRESSURE': {
    id: 'FAM-GEN0110-FLUID-PRESSURE',
    courseId: 'COURSE-GEN0110',
    primarySkillId: 'SKILL-GEN0110-001',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Hydrostatic Pressure and Pascal Principle Calculation',
    description: 'Compute hydrostatic gauge and absolute pressure P = P0 + rho*g*h in hydraulic columns and submerged gates.',
    purpose: 'Assesses physical fluid statics calculations with density and gravity acceleration.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'VERBAL', 'NUMERIC'],
    allowedContexts: ['PHYSICS', 'FLUID_STATICS'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['GAUGE_VS_ABSOLUTE_CONFUSION', 'DENSITY_UNIT_SCALE_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-GEN0110-FLUID-PRESSURE'],
    domainValidatorType: 'PHYSICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0110-BUOYANCY-ARCHIMEDES': {
    id: 'FAM-GEN0110-BUOYANCY-ARCHIMEDES',
    courseId: 'COURSE-GEN0110',
    primarySkillId: 'SKILL-GEN0110-001',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Archimedes Principle and Submerged Buoyant Force Calculation',
    description: 'Calculate buoyant upward force F_b = rho_fluid * V_submerged * g and determine submerged fraction.',
    purpose: 'Assesses static equilibrium of floating and submerged bodies.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'VERBAL'],
    allowedContexts: ['PHYSICS', 'FLUID_STATICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['FLUID_DENSITY_VS_OBJECT_DENSITY_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0110-001'],
    templateIds: ['TMPL-GEN0110-BUOYANCY-ARCHIMEDES'],
    domainValidatorType: 'PHYSICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0110-HEAT-CONDUCTION': {
    id: 'FAM-GEN0110-HEAT-CONDUCTION',
    courseId: 'COURSE-GEN0110',
    primarySkillId: 'SKILL-GEN0110-002',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Fourier Law 1D Steady Heat Conduction through Plane Walls',
    description: 'Compute thermal heat transfer rate Q/t = k * A * (T_hot - T_cold) / L across insulating materials.',
    purpose: 'Assesses Fourier conduction calculations, thermal conductivity units, and temperature gradients.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION', 'INTERPRETATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'NUMERIC'],
    allowedContexts: ['PHYSICS', 'HEAT_TRANSFER'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['THERMAL_THICKNESS_RECIPROCAL_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-GEN0110-HEAT-CONDUCTION'],
    domainValidatorType: 'PHYSICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0110-DC-CIRCUITS-OHM': {
    id: 'FAM-GEN0110-DC-CIRCUITS-OHM',
    courseId: 'COURSE-GEN0110',
    primarySkillId: 'SKILL-GEN0110-008',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Direct Current Resistor Network and Ohm Law Analysis',
    description: 'Calculate equivalent series-parallel resistance, branch currents, and node voltages using Ohm Law (V = IR).',
    purpose: 'Assesses circuit reduction and algebraic current loop analysis.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION', 'ERROR_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'SCHEMATIC_DIAGRAM'],
    allowedContexts: ['CIRCUITS', 'PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['SERIES_PARALLEL_FORMULA_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-GEN0110-DC-CIRCUITS-OHM'],
    domainValidatorType: 'PHYSICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0110-COULOMB-FORCE': {
    id: 'FAM-GEN0110-COULOMB-FORCE',
    courseId: 'COURSE-GEN0110',
    primarySkillId: 'SKILL-GEN0110-007',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Coulomb Law Electrostatic Force and Electric Field Calculation',
    description: 'Calculate electrostatic force F = k * |q1 * q2| / r^2 between point charges and electric field E = F/q.',
    purpose: 'Assesses inverse-square Coulomb forces and micro-Coulomb unit conversions.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'NUMERIC'],
    allowedContexts: ['PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['MICRO_COULOMB_METRIC_PREFIX_ERROR', 'INVERSE_SQUARE_DISTANCE_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-GEN0110-COULOMB-FORCE'],
    domainValidatorType: 'PHYSICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0110-SNELL-REFRACTION': {
    id: 'FAM-GEN0110-SNELL-REFRACTION',
    courseId: 'COURSE-GEN0110',
    primarySkillId: 'SKILL-GEN0110-009',
    supportingSkillIds: ['SKILL-GEN0101-010'],
    name: 'Snell Law Optical Refraction and Critical Angle Calculation',
    description: 'Calculate refracted ray angle n1 * sin(theta1) = n2 * sin(theta2) and critical angle for total internal reflection.',
    purpose: 'Assesses optical wave refraction and geometric optics angle analysis.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'GRAPHICAL'],
    allowedContexts: ['PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['NORMAL_VS_SURFACE_ANGLE_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0101-010'],
    templateIds: ['TMPL-GEN0110-SNELL-REFRACTION'],
    domainValidatorType: 'PHYSICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0110-DOPPLER-SHIFT': {
    id: 'FAM-GEN0110-DOPPLER-SHIFT',
    courseId: 'COURSE-GEN0110',
    primarySkillId: 'SKILL-GEN0110-005',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Doppler Frequency Shift for Moving Acoustic Sources and Observers',
    description: 'Calculate perceived acoustic frequency f\' = f * (v +- v_o) / (v -+ v_s) for approaching/receding sources.',
    purpose: 'Assesses acoustic wave mechanics and relative motion sign conventions.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'VERBAL'],
    allowedContexts: ['PHYSICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['DOPPLER_APPROACHING_SIGN_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-GEN0110-DOPPLER-SHIFT'],
    domainValidatorType: 'PHYSICS',
    status: 'ACTIVE'
  },

  // =========================================================================
  // COURSE: GEN 0161 (Thermodynamics)
  // =========================================================================
  'FAM-GEN0161-STATE-PROPERTY-TABLE': {
    id: 'FAM-GEN0161-STATE-PROPERTY-TABLE',
    courseId: 'COURSE-GEN0161',
    primarySkillId: 'SKILL-GEN0161-005',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Thermodynamic Phase State Identification and Table Lookup',
    description: 'Determine water or refrigerant phase (compressed liquid, saturated mixture, superheated vapor) and extract properties (v, u, h, s).',
    purpose: 'Assesses thermodynamic state postulate application and property table interpretation.',
    primaryEvidenceType: 'TABLE_INTERPRETATION',
    secondaryEvidenceTypes: ['INTERPRETATION', 'DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'MULTIPLE_CHOICE'],
    representationTypes: ['TABULAR', 'PHYSICAL'],
    allowedContexts: ['THERMODYNAMICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['SATURATED_VS_SUPERHEATED_CONFUSION', 'QUALITY_FORMULA_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-GEN0161-STATE-PROPERTY-TABLE'],
    domainValidatorType: 'THERMODYNAMICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0161-BOUNDARY-WORK-IDEAL': {
    id: 'FAM-GEN0161-BOUNDARY-WORK-IDEAL',
    courseId: 'COURSE-GEN0161',
    primarySkillId: 'SKILL-GEN0161-004',
    supportingSkillIds: ['SKILL-GEN0102-001'],
    name: 'Ideal Gas Boundary Work Evaluation for Constant Pressure and Isothermal Processes',
    description: 'Calculate boundary work W = P*Delta V (isobaric) or W = P1*V1*ln(V2/V1) (isothermal) in piston cylinders.',
    purpose: 'Assesses quasi-equilibrium PV boundary work integration.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'NUMERIC'],
    allowedContexts: ['THERMODYNAMICS'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['ISOTHERMAL_LOG_VOLUME_RATIO_FLIP'],
    prerequisiteRequirements: ['SKILL-GEN0102-001'],
    templateIds: ['TMPL-GEN0161-BOUNDARY-WORK-IDEAL'],
    domainValidatorType: 'THERMODYNAMICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0161-1ST-LAW-CLOSED': {
    id: 'FAM-GEN0161-1ST-LAW-CLOSED',
    courseId: 'COURSE-GEN0161',
    primarySkillId: 'SKILL-GEN0161-002',
    supportingSkillIds: ['SKILL-GEN0161-003'],
    name: 'First Law Closed System Energy Balance',
    description: 'Apply First Law Q - W = Delta U = m*(u2 - u1) for stationary closed system processes.',
    purpose: 'Assesses energy conservation balances and heat/work sign conventions.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'VERBAL'],
    allowedContexts: ['THERMODYNAMICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['WORK_HEAT_SIGN_CONVENTION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0161-003'],
    templateIds: ['TMPL-GEN0161-1ST-LAW-CLOSED'],
    domainValidatorType: 'THERMODYNAMICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0161-1ST-LAW-OPEN-DEVICE': {
    id: 'FAM-GEN0161-1ST-LAW-OPEN-DEVICE',
    courseId: 'COURSE-GEN0161',
    primarySkillId: 'SKILL-GEN0161-005',
    supportingSkillIds: ['SKILL-GEN0161-004'],
    name: 'Steady-Flow First Law Open System Devices (Turbines, Compressors, Nozzles)',
    description: 'Calculate shaft work W_dot = m_dot * (h_in - h_out) or exit velocity for steady-flow open engineering devices.',
    purpose: 'Assesses mass and energy conservation across open thermodynamic control volumes.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['MULTI_STEP_SOLUTION', 'UNIT_ANALYSIS'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'SCHEMATIC_DIAGRAM'],
    allowedContexts: ['THERMODYNAMICS', 'GENERAL_ENGINEERING'],
    difficultyRange: [3, 5],
    misconceptionTargets: ['ENTHALPY_VS_INTERNAL_ENERGY_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0161-004'],
    templateIds: ['TMPL-GEN0161-1ST-LAW-OPEN-DEVICE'],
    domainValidatorType: 'THERMODYNAMICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0161-CARNOT-EFFICIENCY': {
    id: 'FAM-GEN0161-CARNOT-EFFICIENCY',
    courseId: 'COURSE-GEN0161',
    primarySkillId: 'SKILL-GEN0161-006',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Carnot Heat Engine Maximum Thermal Efficiency and Reversible COP',
    description: 'Calculate maximum theoretical thermal efficiency eta_th = 1 - T_L / T_H using absolute Kelvin temperatures.',
    purpose: 'Assesses Second Law of Thermodynamics efficiency upper bounds and Kelvin conversion.',
    primaryEvidenceType: 'COMPARISON',
    secondaryEvidenceTypes: ['EXPLANATION', 'DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'MULTIPLE_CHOICE'],
    representationTypes: ['PHYSICAL', 'NUMERIC'],
    allowedContexts: ['THERMODYNAMICS'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['CELSIUS_TEMPERATURE_SUBSTITUTION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-GEN0161-CARNOT-EFFICIENCY'],
    domainValidatorType: 'THERMODYNAMICS',
    status: 'ACTIVE'
  },
  'FAM-GEN0161-IDEAL-GAS-ENTROPY': {
    id: 'FAM-GEN0161-IDEAL-GAS-ENTROPY',
    courseId: 'COURSE-GEN0161',
    primarySkillId: 'SKILL-GEN0161-006',
    supportingSkillIds: ['SKILL-GEN0102-007'],
    name: 'Ideal Gas Entropy Change Evaluation (T-ds Relations)',
    description: 'Compute entropy change Delta s = c_p * ln(T2/T1) - R * ln(P2/P1) for ideal gases.',
    purpose: 'Assesses T-ds relations and logarithmic pressure/temperature ratio scaling.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['TABLE_INTERPRETATION', 'APPLICATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['PHYSICAL', 'SYMBOLIC'],
    allowedContexts: ['THERMODYNAMICS'],
    difficultyRange: [3, 5],
    misconceptionTargets: ['CP_VS_CV_SELECTION_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0102-007'],
    templateIds: ['TMPL-GEN0161-IDEAL-GAS-ENTROPY'],
    domainValidatorType: 'THERMODYNAMICS',
    status: 'ACTIVE'
  },

  // =========================================================================
  // COURSE: BSIE 3219 (IE Special Topics 1)
  // =========================================================================
  'FAM-BSIE3219-COMPOUND-INTEREST': {
    id: 'FAM-BSIE3219-COMPOUND-INTEREST',
    courseId: 'COURSE-BSIE3219',
    primarySkillId: 'SKILL-BSIE3219-006',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Engineering Economy Single-Payment Compound Future Worth',
    description: 'Calculate Future Worth F = P * (1 + i)^n or Present Worth P = F * (1 + i)^-n.',
    purpose: 'Assesses time value of money discrete compounding formulas.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['NUMERIC', 'VERBAL'],
    allowedContexts: ['ENGINEERING_ECONOMY'],
    difficultyRange: [1, 3],
    misconceptionTargets: ['SIMPLE_VS_COMPOUND_INTEREST_CONFUSION'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-BSIE3219-COMPOUND-INTEREST'],
    domainValidatorType: 'IE_SPECIAL_TOPICS',
    status: 'ACTIVE'
  },
  'FAM-BSIE3219-UNIFORM-ANNUITY': {
    id: 'FAM-BSIE3219-UNIFORM-ANNUITY',
    courseId: 'COURSE-BSIE3219',
    primarySkillId: 'SKILL-BSIE3219-007',
    supportingSkillIds: ['SKILL-BSIE3219-001'],
    name: 'Uniform Series Annuity Present Worth and Capital Recovery (P/A, A/P)',
    description: 'Compute Present Worth P = A * [((1+i)^n - 1) / (i*(1+i)^n)] of uniform annual cash flows.',
    purpose: 'Assesses engineering economy annuity series conversion factors.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['NUMERIC', 'VERBAL'],
    allowedContexts: ['ENGINEERING_ECONOMY'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['ANNUITY_PERIOD_COUNT_ERROR'],
    prerequisiteRequirements: ['SKILL-BSIE3219-001'],
    templateIds: ['TMPL-BSIE3219-UNIFORM-ANNUITY'],
    domainValidatorType: 'IE_SPECIAL_TOPICS',
    status: 'ACTIVE'
  },
  'FAM-BSIE3219-DEPRECIATION-SCHEDULE': {
    id: 'FAM-BSIE3219-DEPRECIATION-SCHEDULE',
    courseId: 'COURSE-BSIE3219',
    primarySkillId: 'SKILL-BSIE3219-008',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Asset Depreciation Schedule Calculation (Straight-Line & MACRS)',
    description: 'Compute annual depreciation D_t = (C - S)/N and asset book value BV_t = C - sum(D).',
    purpose: 'Assesses asset accounting, salvage value subtraction, and tax depreciation schedules.',
    primaryEvidenceType: 'DIRECT_CALCULATION',
    secondaryEvidenceTypes: ['APPLICATION'],
    supportedFormats: ['NUMERIC_INPUT', 'TABLE_INPUT'],
    representationTypes: ['NUMERIC', 'TABULAR'],
    allowedContexts: ['ENGINEERING_ECONOMY'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['SALVAGE_VALUE_OMISSION_STRAIGHT_LINE'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-BSIE3219-DEPRECIATION-SCHEDULE'],
    domainValidatorType: 'IE_SPECIAL_TOPICS',
    status: 'ACTIVE'
  },
  'FAM-BSIE3219-BENEFIT-COST-ANALYSIS': {
    id: 'FAM-BSIE3219-BENEFIT-COST-ANALYSIS',
    courseId: 'COURSE-BSIE3219',
    primarySkillId: 'SKILL-BSIE3219-009',
    supportingSkillIds: ['SKILL-BSIE3219-001'],
    name: 'Benefit-Cost Ratio (B/C) Public Project Economic Feasibility Evaluation',
    description: 'Calculate conventional B/C = PW(Benefits) / PW(Costs) and evaluate if B/C >= 1.0.',
    purpose: 'Assesses economic evaluation and decision justification of public works engineering proposals.',
    primaryEvidenceType: 'COMPARISON',
    secondaryEvidenceTypes: ['APPLICATION', 'DESIGN_SELECTION'],
    supportedFormats: ['NUMERIC_INPUT', 'MULTIPLE_CHOICE'],
    representationTypes: ['NUMERIC', 'VERBAL'],
    allowedContexts: ['ENGINEERING_ECONOMY', 'LICENSURE_STYLE'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['DISBENEFITS_PLACEMENT_ERROR'],
    prerequisiteRequirements: ['SKILL-BSIE3219-001'],
    templateIds: ['TMPL-BSIE3219-BENEFIT-COST-ANALYSIS'],
    domainValidatorType: 'IE_SPECIAL_TOPICS',
    status: 'ACTIVE'
  },
  'FAM-BSIE3219-LINEAR-PROGRAMMING': {
    id: 'FAM-BSIE3219-LINEAR-PROGRAMMING',
    courseId: 'COURSE-BSIE3219',
    primarySkillId: 'SKILL-BSIE3219-006',
    supportingSkillIds: ['SKILL-GEN0101-009'],
    name: 'Linear Programming Production Mix Formulation and Corner Point Evaluation',
    description: 'Formulate objective Max Z = c1*x1 + c2*x2 subject to resource constraints and evaluate corner point optima.',
    purpose: 'Assesses operations research model formulation and graphical linear programming.',
    primaryEvidenceType: 'MODEL_FORMULATION',
    secondaryEvidenceTypes: ['APPLICATION', 'DIRECT_CALCULATION'],
    supportedFormats: ['FREE_RESPONSE', 'MULTIPLE_CHOICE'],
    representationTypes: ['SYMBOLIC', 'GRAPHICAL'],
    allowedContexts: ['INDUSTRIAL_ENGINEERING'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['INEQUALITY_DIRECTION_FLIP'],
    prerequisiteRequirements: ['SKILL-GEN0101-009'],
    templateIds: ['TMPL-BSIE3219-LINEAR-PROGRAMMING'],
    domainValidatorType: 'IE_SPECIAL_TOPICS',
    status: 'ACTIVE'
  },
  'FAM-BSIE3219-CPM-PERT-NETWORK': {
    id: 'FAM-BSIE3219-CPM-PERT-NETWORK',
    courseId: 'COURSE-BSIE3219',
    primarySkillId: 'SKILL-BSIE3219-007',
    supportingSkillIds: ['SKILL-GEN0101-001'],
    name: 'Project Management Critical Path Method (CPM/PERT) Network Analysis',
    description: 'Calculate Early Start (ES), Early Finish (EF), and total slack to determine critical path duration.',
    purpose: 'Assesses project scheduling forward and backward pass calculations.',
    primaryEvidenceType: 'APPLICATION',
    secondaryEvidenceTypes: ['DIRECT_CALCULATION'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['GRAPHICAL', 'NUMERIC'],
    allowedContexts: ['INDUSTRIAL_ENGINEERING'],
    difficultyRange: [2, 4],
    misconceptionTargets: ['BACKWARD_PASS_MIN_PRECEDENCE_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0101-001'],
    templateIds: ['TMPL-BSIE3219-CPM-PERT-NETWORK'],
    domainValidatorType: 'IE_SPECIAL_TOPICS',
    status: 'ACTIVE'
  },
  'FAM-BSIE3219-EOQ-INVENTORY': {
    id: 'FAM-BSIE3219-EOQ-INVENTORY',
    courseId: 'COURSE-BSIE3219',
    primarySkillId: 'SKILL-BSIE3219-009',
    supportingSkillIds: ['SKILL-GEN0102-014'],
    name: 'Economic Order Quantity (EOQ) Optimal Batch Size Calculation',
    description: 'Calculate optimal inventory lot size EOQ = sqrt(2*D*S / H) balancing setup and holding costs.',
    purpose: 'Assesses cost minimization trade-offs in industrial supply chain management.',
    primaryEvidenceType: 'DESIGN_SELECTION',
    secondaryEvidenceTypes: ['APPLICATION', 'COMPARISON'],
    supportedFormats: ['NUMERIC_INPUT', 'FREE_RESPONSE'],
    representationTypes: ['NUMERIC', 'VERBAL'],
    allowedContexts: ['INDUSTRIAL_ENGINEERING', 'ENGINEERING_ECONOMY'],
    difficultyRange: [2, 3],
    misconceptionTargets: ['ANNUAL_HOLDING_COST_PERCENTAGE_ERROR'],
    prerequisiteRequirements: ['SKILL-GEN0102-014'],
    templateIds: ['TMPL-BSIE3219-EOQ-INVENTORY'],
    domainValidatorType: 'IE_SPECIAL_TOPICS',
    status: 'ACTIVE'
  }
};

// Keep every authoritative skill selectable. Hand-authored families take
// precedence; missing skills receive a clearly labelled representative
// blueprint until richer teacher-reviewed variants are added.
for (const skill of curriculumRegistry.getAllSkills()) {
  const hasFamily = Object.values(PROBLEM_FAMILIES_REGISTRY).some(f => f.primarySkillId === skill.id);
  if (!hasFamily) {
    const evidence = SIX_COURSE_SKILL_EVIDENCE_MAP[skill.id]?.primaryEvidence;
    const fallback = createFallbackFamily(skill, evidence);
    PROBLEM_FAMILIES_REGISTRY[fallback.id] = fallback;
  }
}
